version: "3.7"
services:
  back:
    build: ./server
    restart: on-failure
    ports:
      - 8080:8080

  front:
    build: ./client
    restart: on-failure
    depends_on:
      - back
    ports:
      - 3000:3000
